module.exports = [
  'cacheResult',
  'canAccess',
  'consumeArgs',
  'errorHandlers',
  'invalidateCache',
  'jwtToSession',
  'preloadAssets',
  'multistepFormData',
  'multistepFormNav',
  'redirect',
  'requestLogger',
  'requireAuth',
  'requireCSRF',
  'requireSessionAuth',
  'sendEmail',
  'tryCache',
  'useArgs',
  'useCSRF',
  'useFlash',
  'validateArgs',
  'viewJSON',
  'viewTemplate',
  'wrap',
].reduce((exports, name) => ({
  ...exports,
  [name]: require(`./${name}`),
}), {});
