module.exports = (ctx, serviceLoader) => serviceLoader(ctx, [
  'hook',
  'init',
  'env',
  'db',
  'project',
  'migration',
  'seed',
  'view',
  'module',
  'setting',
  'redis',
  'model',
  'route',
  'acl',
  'asset',
  'menu',
  'controller',
  'httpController',
  'webController',
  'apiController',
  'cliController',
  'cache',
  'template',
  'email',
], __dirname);
